language: node_js

cache: yarn

install: yarn install --ignore-engines

script:
  - yarn test:coverage
  - yarn lint:check
  - yarn format:check

after_success: yarn run coveralls < ./coverage/lcov.info

matrix:
  include:
    - os: linux
      node_js: node
    - os: linux
      node_js: "lts/*"
    - os: osx
      node_js: node
    - os: osx
      node_js: "lts/*"
    - os: windows
      # Fix for build timeouts on Windows: https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
      env: YARN_GPG=no
      before_install:
        # OpenSSL is required for hap-nodejs
        - curl "https://slproweb.com/download/Win64OpenSSL-1_1_1b.exe" --output "/c/Win64OpenSSL.exe"
        - powershell.exe -Command "Start-Process \"C:/Win64OpenSSL.exe\" -ArgumentList \"/silent /verysilent /sp- /suppressmsgboxes\" -Wait"
      node_js: latest
    - os: windows
      env: YARN_GPG=no
      before_install:
        - curl "https://slproweb.com/download/Win64OpenSSL-1_1_1b.exe" --output "/c/Win64OpenSSL.exe"
        - powershell.exe -Command "Start-Process \"C:/Win64OpenSSL.exe\" -ArgumentList \"/silent /verysilent /sp- /suppressmsgboxes\" -Wait"
      node_js: lts

stages:
  - test
