language: node_js

cache: yarn

install: yarn install --ignore-engines

script: yarn test:coverage

after_success: yarn run coveralls < ./coverage/lcov.info

stages:
  - "Test"
  - "Lint"
  - "Check Format"

matrix:
  include:
    - stage: "Test"
      os: linux
      node_js: node
    - stage: "Test"
      os: linux
      node_js: "lts/*"
    - stage: "Test"
      os: osx
      node_js: node
    - stage: "Test"
      os: osx
      node_js: "lts/*"
    - stage: "Test"
      os: windows
      # Fix for build timeouts on Windows: https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
      env: YARN_GPG=no
      before_install:
        - ./scripts/disable-windows-defender-realtime-monitor
        - ./scripts/install-latest-openssl
      node_js: latest
    - stage: "Test"
      os: windows
      env: YARN_GPG=no
      before_install:
        - ./scripts/disable-windows-defender-realtime-monitor
        - ./scripts/install-latest-openssl
      node_js: lts
    - stage: "Lint"
      os: linux
      node_js: "lts/*"
      script: yarn lint:check
      after_success: skip
    - stage: "Check Format"
      os: linux
      node_js: "lts/*"
      script: yarn format:check
      after_success: skip
