language: node_js

cache: yarn

before_install: yarn install --ignore-engines

matrix:
  include:
    - os: linux
      node_js: node
    - os: linux
      node_js: "lts/*"
    - os: osx
      node_js: node
    - os: osx
      node_js: "lts/*"
    - os: windows
      # Fix for build timeouts on Windows: https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
      env: YARN_GPG=no
      # ignore-scripts flag stops the hap-nodejs scripts running, which fail on Windows on Travis
      before_install: yarn install --ignore-engines --ignore-scripts
      node_js: latest
    - os: windows
      env: YARN_GPG=no
      before_install: yarn install --ignore-engines --ignore-scripts
      node_js: lts

stages:
  - test
